version: "3.9"

services:
  deb:
    build: .
    container_name: debian
    hostname: debian
    init: true
    tty: true
    entrypoint: sh -c "/entrypoint.sh"

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - debian-bashhistory:/home/appuser/commandhistory
      - ~/:/home/appuser
      - /usr/share/bash-completion/completions/git:/usr/share/bash-completion/completions/git
      - /usr/local/bin/virtualenvwrapper.sh:/usr/local/bin/virtualenvwrapper.sh

    env_file:
      - .env

volumes:
  debian-bashhistory: # нужен только для отладки
